### ISSUE TITLE
Take fees from order margin on position close

### ISSUE THREAD

**Issue by kappacappa** [capofficial/contracts#1]
When a user closes a position, fees should be taken from the order's margin instead of charging the user's wallet. 

To achieve this, no fees should be charged upfront for reduce-only orders. At execution time (triggered by the oracle), a fee is calculated and taken from the remaining margin. 

If P/L is negative, P/L + fee could exceed the remaining margin, resulting in a liquidation.
If P/L is positive, send P/L minus fee back to the user.

---

### Bounty
* This issue has a bounty of **$250**, paid in crypto. 
* Bounties are paid upon full resolution of the issue with high quality code, within a reasonable timeframe.
* Important: To be eligible for the bounty, comment below to request assignment to this issue.

**Comment by trust0212** [comment]
Please assign this to me.

**Comment by trust0212** [comment]
Hi @kappacappa 
Created a pull request #9 .
