### ISSUE TITLE
Connect to with team

### ISSUE THREAD

**Issue by Atarpara** [capofficial/contracts#15]

**Comment by Atarpara** [comment]
@kappacappa How i can connect you regarding this https://capfinance.medium.com/v4-bug-bounty-program-e9172b3d468a.
I can't find you on discord with (kappa#8972). My discord id is (Atarpara#3852).

**Comment by kappacappa** [comment]
@Atarpara you ccan join the discord server here: https://discord.gg/zkdr8vnujz and then DM me
